"""changed report path to be nullable

Revision ID: 6672a2907d15
Revises: 2173e6e6d0b0
Create Date: 2026-07-12 02:10:37.424595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6672a2907d15'
down_revision: Union[str, Sequence[str], None] = '5b464f7a5b87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'pdf_storage_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'pdf_storage_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
